### ISSUE TITLE
could not access file "$libdir/postgis-2.4"

### ISSUE THREAD

**Issue by JerryGreen** [appropriate/docker-postgis#122]
I'm using rails API with this `mdillon/postgis:9.6` and got this error stacktrace:

```
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
             (SELECT c.collname FROM pg_collation c, pg_type t
               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                     col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"acts"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `async_exec'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `block in query'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
	from /usr/local/bundle/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:87:in `query'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:739:in `column_definitions'
	from /usr/local/bundle/gems/activerecord-postgis-adapter-4.0.3/lib/active_record/connection_adapters/postgis/schema_statements.rb:9:in `columns'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/connection_adapters/schema_cache.rb:62:in `columns_hash'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:442:in `load_schema!'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/attributes.rb:233:in `load_schema!'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/attribute_decorators.rb:28:in `load_schema!'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:437:in `load_schema'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:349:in `attribute_types'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/model_schema.rb:368:in `type_for_attribute'
... 16 levels...
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/association.rb:97:in `association_scope'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/association.rb:86:in `scope'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/collection_association.rb:459:in `scope'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/collection_proxy.rb:36:in `initialize'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:101:in `new'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:101:in `create'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/collection_association.rb:47:in `reader'
	from /usr/local/bundle/gems/activerecord-5.0.2/lib/active_record/associations/builder/association.rb:111:in `acts'
	from (irb):5
	from /usr/local/bundle/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/bundle/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/bundle/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/bundle/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/bundle/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:10:in `require'
	from bin/rails:10:in `<main>'
```

Btw, I have already used that hack (it doesn't help):
```
docker exec some-postgis update-postgis.sh
```

**Comment by JerryGreen** [comment]
It wasn't a problem some time ago. But then you updated the `9.6` (I understand you are trying to have the version names that are used by postgres - but it's still weird to get errors from this docker container because of its updates - this situation happened not the first time with your container - that's definitely a problem!)...

**Comment by JerryGreen** [comment]
Looks like `docker exec some-postgis update-postgis.sh` fix works just for default db (named `postgres`?)

So I had to do this:

```
psql -d your_database_name -c 'alter extension postgis update'
```

Now it's ok but there's still a problem with versioning, I've created [a separate issue](https://github.com/appropriate/docker-postgis/issues/123) for that

**Comment by c0bra** [comment]
@JerryGreen thanks a million

**Comment by JerryGreen** [comment]
@c0bra yea, but the core problem why this all happened is this - https://github.com/appropriate/docker-postgis/issues/123

You can add reaction/smile there to get some potential attention to this problem. Have a good day!
